language: python
sudo: false
cache: pip
env:
  - TOXENV=py38-django30
  - TOXENV=py39-django30
  - TOXENV=py310-django30
  - TOXENV=py38-django40
  - TOXENV=py39-django40
  - TOXENV=py310-django40
  - TOXENV=docs
  - TOXENV=lint
matrix:
  include:
    - python: "3.8"
      env: TOXENV=py38-django30
    - python: "3.9"
      env: TOXENV=py39-django30
    - python: "3.10"
      env: TOXENV=py310-django30
    - python: "3.8"
      env: TOXENV=py38-django40
    - python: "3.9"
      env: TOXENV=py39-django40
    - python: "3.10"
      env: TOXENV=py310-django40
    - python: "3.9"
      env: TOXENV=docs
    - python: "3.9"
      env: TOXENV=lint
install:
  - pip install tox
script:
  - tox -e $TOXENV
